neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "password"

blockcypher:
  api_key: "your_api_key_here"
  timeout: 30

analysis:
  time_window_hours: 24
  min_transactions: 5
  volume_threshold: 1000000  # in satoshis

risk_scoring:
  volume_weight: 0.3
  frequency_weight: 0.2
  layering_weight: 0.3
  smurfing_weight: 0.2
