version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: chainbreak-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_logs_debug_level=INFO
      - NEO4J_dbms_security_allow__upgrade=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_shell_host=0.0.0.0
      - NEO4J_dbms_shell_port=1337
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - neo4j_conf:/var/lib/neo4j/conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - chainbreak-network

  # Optional: Neo4j Browser for development
  neo4j-browser:
    image: neo4j/neo4j-browser:latest
    container_name: chainbreak-neo4j-browser
    ports:
      - "7475:7475"
    environment:
      - NEO4J_BROWSER_NEO4J_URL=bolt://neo4j:7687
      - NEO4J_BROWSER_NEO4J_USERNAME=neo4j
      - NEO4J_BROWSER_NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - chainbreak-network
    profiles:
      - browser

  # ChainBreak Application
  chainbreak-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chainbreak-app
    ports:
      - "5000:5000"
      - "3000:3000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chainbreak-network
    profiles:
      - app

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  neo4j_conf:
    driver: local

networks:
  chainbreak-network:
    driver: bridge
